export const SCHEDULE_TODAY_FETCHING = 'SCHEDULE_TODAY_FETCHING';
export const SCHEDULE_TODAY_LOADED = 'SCHEDULE_TODAY_LOADED';
export const SCHEDULE_TODAY_FAILURE = 'SCHEDULE_TODAY_FAILURE';

export const NEXT_SCHEDULE_FETCHING = 'NEXT_SCHEDULE_FETCHING';
export const NEXT_SCHEDULE_LOADED = 'NEXT_SCHEDULE_LOADED';
export const NEXT_SCHEDULE_FAILURE = 'NEXT_SCHEDULE_FAILURE';
